/**
 * @file cmc_can_message.h
 *
 * @brief This header file was generated by cantools version 41.3.0 Mon Apr  6 23:03:56 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CMC_CAN_MESSAGE_H
#define CMC_CAN_MESSAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CMC_CAN_MESSAGE_HANDSHAKE_FRAME_ID (0x64u)
#define CMC_CAN_MESSAGE_HEARTBEAT_FRAME_ID (0x65u)

/* Frame lengths in bytes. */
#define CMC_CAN_MESSAGE_HANDSHAKE_LENGTH (16u)
#define CMC_CAN_MESSAGE_HEARTBEAT_LENGTH (2u)

/* Extended or standard frame types. */
#define CMC_CAN_MESSAGE_HANDSHAKE_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_HEARTBEAT_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_TYPE_UNKNOWN_CHOICE (0u)
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_TYPE_I_O_UNIT_CHOICE (1u)

#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_UNKNOWN_CHOICE (0u)
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_OK_CHOICE (1u)
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_WARNING_CHOICE (2u)
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_FAULT_CHOICE (3u)

/* Frame Names. */
#define CMC_CAN_MESSAGE_HANDSHAKE_NAME "HANDSHAKE"
#define CMC_CAN_MESSAGE_HEARTBEAT_NAME "HEARTBEAT"

/* Signal Names. */
#define CMC_CAN_MESSAGE_HANDSHAKE_HW_VERSION_MAJOR_NAME "hw_version_major"
#define CMC_CAN_MESSAGE_HANDSHAKE_HW_VERSION_MINOR_NAME "hw_version_minor"
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_ID_NAME "unit_id"
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_TYPE_NAME "unit_type"
#define CMC_CAN_MESSAGE_HANDSHAKE_FW_VERSION_MAJOR_NAME "fw_version_major"
#define CMC_CAN_MESSAGE_HANDSHAKE_FW_VERSION_MINOR_NAME "fw_version_minor"
#define CMC_CAN_MESSAGE_HANDSHAKE_GC_DATETIME_NAME "gc_datetime"
#define CMC_CAN_MESSAGE_HANDSHAKE_GC_HASH_NAME "gc_hash"
#define CMC_CAN_MESSAGE_HEARTBEAT_UNIT_ID_NAME "unit_id"
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_NAME "system_state"

/**
 * Signals in message HANDSHAKE.
 *
 * Startup init to check ID and FW for all units, inititate reset or reconfig if needed
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_handshake_t {
    /**
     * Hardware major version
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hw_version_major;

    /**
     * Hardware minor version
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hw_version_minor;

    /**
     * Unique ID, to be set automatically if reset to 0
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t unit_id;

    /**
     * Unit type
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t unit_type;

    /**
     * Firmware major version, should listed for compability to ensure units can be combined
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fw_version_major;

    /**
     * Firmware minor version, for info only
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fw_version_minor;

    /**
     * All global configs across all units must be the same, datetime is when the config was created/updated, if not the same across units or if missing, the most recent updated config is to be used and passed over to units with old config
     *
     * Range: 0..4294967295 (0..4294967295 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t gc_datetime;

    /**
     * All global configs actross all units must be the same, this hash represent global config checksum
     *
     * Range: 0..4294967295 (0..4294967295 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t gc_hash;
};

/**
 * Signals in message HEARTBEAT.
 *
 * Poll on system frequently to identify missing units or mishaps
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_heartbeat_t {
    /**
     * Unique ID for the source unit
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t unit_id;

    /**
     * Report system state for taking action if not OK
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t system_state;
};

/**
 * Pack message HANDSHAKE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_handshake_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_handshake_t *src_p,
    size_t size);

/**
 * Unpack message HANDSHAKE.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_handshake_unpack(
    struct cmc_can_message_handshake_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HANDSHAKE.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_handshake_init(struct cmc_can_message_handshake_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_hw_version_major_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_hw_version_major_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_major_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_major_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_hw_version_minor_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_hw_version_minor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_minor_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_minor_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_unit_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_unit_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_id_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_id_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_unit_type_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_unit_type_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_type_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_type_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_fw_version_major_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_fw_version_major_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_major_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_major_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_fw_version_minor_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_fw_version_minor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_minor_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_minor_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t cmc_can_message_handshake_gc_datetime_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_gc_datetime_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_datetime_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_datetime_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t cmc_can_message_handshake_gc_hash_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_gc_hash_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_hash_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_hash_is_in_phys_range(double value);

/**
 * Pack message HEARTBEAT.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_heartbeat_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_heartbeat_t *src_p,
    size_t size);

/**
 * Unpack message HEARTBEAT.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_heartbeat_unpack(
    struct cmc_can_message_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HEARTBEAT.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_heartbeat_init(struct cmc_can_message_heartbeat_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_heartbeat_unit_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_heartbeat_unit_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_unit_id_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_unit_id_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_heartbeat_system_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_heartbeat_system_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_system_state_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_system_state_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
