/**
 * @file cmc_can_message.c
 *
 * @brief This source file was generated by cantools version 41.3.0 Sun Aug  9 17:07:18 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "cmc_can_message.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int cmc_can_message_handshake_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_handshake_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    dst_p[0] |= pack_left_shift_u8(src_p->hw_version_major, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->hw_version_minor, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->unit_id, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->unit_type, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->fw_version_major, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->fw_version_minor, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u32(src_p->gc_datetime, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->gc_datetime, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(src_p->gc_datetime, 16u, 0xffu);
    dst_p[9] |= pack_right_shift_u32(src_p->gc_datetime, 24u, 0xffu);
    dst_p[10] |= pack_left_shift_u32(src_p->gc_hash, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(src_p->gc_hash, 8u, 0xffu);
    dst_p[12] |= pack_right_shift_u32(src_p->gc_hash, 16u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(src_p->gc_hash, 24u, 0xffu);

    return (16);
}

int cmc_can_message_handshake_unpack(
    struct cmc_can_message_handshake_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    dst_p->hw_version_major = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->hw_version_minor = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->unit_id = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->unit_type = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->fw_version_major = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->fw_version_minor = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->gc_datetime = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    dst_p->gc_datetime |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    dst_p->gc_datetime |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);
    dst_p->gc_datetime |= unpack_left_shift_u32(src_p[9], 24u, 0xffu);
    dst_p->gc_hash = unpack_right_shift_u32(src_p[10], 0u, 0xffu);
    dst_p->gc_hash |= unpack_left_shift_u32(src_p[11], 8u, 0xffu);
    dst_p->gc_hash |= unpack_left_shift_u32(src_p[12], 16u, 0xffu);
    dst_p->gc_hash |= unpack_left_shift_u32(src_p[13], 24u, 0xffu);

    return (0);
}

int cmc_can_message_handshake_init(struct cmc_can_message_handshake_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_handshake_t));

    return 0;
}

uint8_t cmc_can_message_handshake_hw_version_major_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_hw_version_major_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_hw_version_major_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_hw_version_major_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_hw_version_minor_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_hw_version_minor_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_hw_version_minor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_hw_version_minor_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_unit_id_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_unit_id_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_unit_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_unit_id_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_unit_type_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_unit_type_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_unit_type_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_unit_type_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_fw_version_major_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_fw_version_major_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_fw_version_major_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_fw_version_major_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_fw_version_minor_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_fw_version_minor_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_fw_version_minor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_fw_version_minor_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint32_t cmc_can_message_handshake_gc_datetime_encode(double value)
{
    return (uint32_t)(value);
}

double cmc_can_message_handshake_gc_datetime_decode(uint32_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_gc_datetime_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_gc_datetime_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967295.0));
}

uint32_t cmc_can_message_handshake_gc_hash_encode(double value)
{
    return (uint32_t)(value);
}

double cmc_can_message_handshake_gc_hash_decode(uint32_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_gc_hash_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_gc_hash_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967295.0));
}

int cmc_can_message_heartbeat_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->unit_id, 0u, 0x3fu);
    dst_p[0] |= pack_left_shift_u8(src_p->system_state, 6u, 0xc0u);

    return (1);
}

int cmc_can_message_heartbeat_unpack(
    struct cmc_can_message_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->unit_id = unpack_right_shift_u8(src_p[0], 0u, 0x3fu);
    dst_p->system_state = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);

    return (0);
}

int cmc_can_message_heartbeat_init(struct cmc_can_message_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_heartbeat_t));

    return 0;
}

uint8_t cmc_can_message_heartbeat_unit_id_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_heartbeat_unit_id_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_heartbeat_unit_id_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool cmc_can_message_heartbeat_unit_id_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 63.0));
}

uint8_t cmc_can_message_heartbeat_system_state_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_heartbeat_system_state_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_heartbeat_system_state_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool cmc_can_message_heartbeat_system_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

int cmc_can_message_feature_horn_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_horn_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->horn_on, 0u, 0x01u);

    return (1);
}

int cmc_can_message_feature_horn_unpack(
    struct cmc_can_message_feature_horn_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->horn_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int cmc_can_message_feature_horn_init(struct cmc_can_message_feature_horn_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_horn_t));

    return 0;
}

uint8_t cmc_can_message_feature_horn_horn_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_horn_horn_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_horn_horn_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_horn_horn_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_feature_direction_indicator_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_direction_indicator_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->turn_signal_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->turn_signal_direction, 1u, 0x06u);
    dst_p[0] |= pack_left_shift_u8(src_p->turn_signal_position, 3u, 0x18u);
    dst_p[0] |= pack_left_shift_u8(src_p->dashboard_only, 5u, 0x20u);

    return (1);
}

int cmc_can_message_feature_direction_indicator_unpack(
    struct cmc_can_message_feature_direction_indicator_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->turn_signal_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->turn_signal_direction = unpack_right_shift_u8(src_p[0], 1u, 0x06u);
    dst_p->turn_signal_position = unpack_right_shift_u8(src_p[0], 3u, 0x18u);
    dst_p->dashboard_only = unpack_right_shift_u8(src_p[0], 5u, 0x20u);

    return (0);
}

int cmc_can_message_feature_direction_indicator_init(struct cmc_can_message_feature_direction_indicator_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_direction_indicator_t));

    return 0;
}

uint8_t cmc_can_message_feature_direction_indicator_turn_signal_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_turn_signal_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_turn_signal_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_direction_indicator_turn_signal_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_feature_direction_indicator_turn_signal_direction_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_turn_signal_direction_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_turn_signal_direction_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool cmc_can_message_feature_direction_indicator_turn_signal_direction_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 2.0));
}

uint8_t cmc_can_message_feature_direction_indicator_turn_signal_position_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_turn_signal_position_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_turn_signal_position_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool cmc_can_message_feature_direction_indicator_turn_signal_position_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 2.0));
}

uint8_t cmc_can_message_feature_direction_indicator_dashboard_only_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_dashboard_only_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_dashboard_only_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_direction_indicator_dashboard_only_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_feature_ignition_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_ignition_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->ignition_on, 0u, 0x01u);

    return (1);
}

int cmc_can_message_feature_ignition_unpack(
    struct cmc_can_message_feature_ignition_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->ignition_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int cmc_can_message_feature_ignition_init(struct cmc_can_message_feature_ignition_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_ignition_t));

    return 0;
}

uint8_t cmc_can_message_feature_ignition_ignition_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_ignition_ignition_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_ignition_ignition_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_ignition_ignition_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_feature_starter_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_starter_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->starter_on, 0u, 0x01u);

    return (1);
}

int cmc_can_message_feature_starter_unpack(
    struct cmc_can_message_feature_starter_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->starter_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int cmc_can_message_feature_starter_init(struct cmc_can_message_feature_starter_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_starter_t));

    return 0;
}

uint8_t cmc_can_message_feature_starter_starter_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_starter_starter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_starter_starter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_starter_starter_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_feature_light_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_light_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->park_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_beam_on, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->high_beam_on, 2u, 0x04u);

    return (1);
}

int cmc_can_message_feature_light_unpack(
    struct cmc_can_message_feature_light_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->park_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->low_beam_on = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->high_beam_on = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    return (0);
}

int cmc_can_message_feature_light_init(struct cmc_can_message_feature_light_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_light_t));

    return 0;
}

uint8_t cmc_can_message_feature_light_park_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_light_park_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_light_park_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_light_park_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_feature_light_low_beam_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_light_low_beam_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_light_low_beam_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_light_low_beam_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_feature_light_high_beam_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_light_high_beam_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_light_high_beam_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_light_high_beam_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_feature_brake_light_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_brake_light_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->brake_light_on, 0u, 0x01u);

    return (1);
}

int cmc_can_message_feature_brake_light_unpack(
    struct cmc_can_message_feature_brake_light_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->brake_light_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int cmc_can_message_feature_brake_light_init(struct cmc_can_message_feature_brake_light_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_brake_light_t));

    return 0;
}

uint8_t cmc_can_message_feature_brake_light_brake_light_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_brake_light_brake_light_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_brake_light_brake_light_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_brake_light_brake_light_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_feature_neutral_sensor_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_neutral_sensor_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->neutral_engaged, 0u, 0x01u);

    return (1);
}

int cmc_can_message_feature_neutral_sensor_unpack(
    struct cmc_can_message_feature_neutral_sensor_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->neutral_engaged = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int cmc_can_message_feature_neutral_sensor_init(struct cmc_can_message_feature_neutral_sensor_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_neutral_sensor_t));

    return 0;
}

uint8_t cmc_can_message_feature_neutral_sensor_neutral_engaged_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_neutral_sensor_neutral_engaged_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_neutral_sensor_neutral_engaged_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_neutral_sensor_neutral_engaged_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_feature_oil_pressure_sensor_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_oil_pressure_sensor_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->oil_pressure_low_detected, 0u, 0x01u);

    return (1);
}

int cmc_can_message_feature_oil_pressure_sensor_unpack(
    struct cmc_can_message_feature_oil_pressure_sensor_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->oil_pressure_low_detected = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int cmc_can_message_feature_oil_pressure_sensor_init(struct cmc_can_message_feature_oil_pressure_sensor_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_oil_pressure_sensor_t));

    return 0;
}

uint8_t cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int cmc_can_message_channel_status_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_channel_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->channel_number, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->is_on, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->status, 5u, 0xe0u);
    dst_p[1] |= pack_left_shift_u16(src_p->watts, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->watts, 8u, 0x7fu);

    return (3);
}

int cmc_can_message_channel_status_unpack(
    struct cmc_can_message_channel_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->channel_number = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->is_on = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->status = unpack_right_shift_u8(src_p[0], 5u, 0xe0u);
    dst_p->watts = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->watts |= unpack_left_shift_u16(src_p[2], 8u, 0x7fu);

    return (0);
}

int cmc_can_message_channel_status_init(struct cmc_can_message_channel_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_channel_status_t));

    return 0;
}

uint8_t cmc_can_message_channel_status_channel_number_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_status_channel_number_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_status_channel_number_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 16u));
}

bool cmc_can_message_channel_status_channel_number_is_in_phys_range(double value)
{
    return ((value >= 1.0) && (value <= 16.0));
}

uint8_t cmc_can_message_channel_status_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_status_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_status_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_status_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_status_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_status_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_status_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_status_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_status_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_status_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_status_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_status_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

int cmc_can_message_channel_overview_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_channel_overview_t *src_p,
    size_t size)
{
    if (size < 32u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 32);

    dst_p[0] |= pack_left_shift_u8(src_p->ch01_is_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ch01_status, 1u, 0x0eu);
    dst_p[0] |= pack_left_shift_u16(src_p->ch01_watts, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->ch01_watts, 4u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->ch01_watts, 12u, 0x07u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch02_is_on, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch02_status, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u16(src_p->ch02_watts, 7u, 0x80u);
    dst_p[3] |= pack_right_shift_u16(src_p->ch02_watts, 1u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->ch02_watts, 9u, 0x3fu);
    dst_p[4] |= pack_left_shift_u8(src_p->ch03_is_on, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->ch03_status, 7u, 0x80u);
    dst_p[5] |= pack_right_shift_u8(src_p->ch03_status, 1u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->ch03_watts, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->ch03_watts, 6u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ch03_watts, 14u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->ch04_is_on, 1u, 0x02u);
    dst_p[7] |= pack_left_shift_u8(src_p->ch04_status, 2u, 0x1cu);
    dst_p[7] |= pack_left_shift_u16(src_p->ch04_watts, 5u, 0xe0u);
    dst_p[8] |= pack_right_shift_u16(src_p->ch04_watts, 3u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(src_p->ch04_watts, 11u, 0x0fu);
    dst_p[9] |= pack_left_shift_u8(src_p->ch05_is_on, 4u, 0x10u);
    dst_p[9] |= pack_left_shift_u8(src_p->ch05_status, 5u, 0xe0u);
    dst_p[10] |= pack_left_shift_u16(src_p->ch05_watts, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(src_p->ch05_watts, 8u, 0x7fu);
    dst_p[11] |= pack_left_shift_u8(src_p->ch06_is_on, 7u, 0x80u);
    dst_p[12] |= pack_left_shift_u8(src_p->ch06_status, 0u, 0x07u);
    dst_p[12] |= pack_left_shift_u16(src_p->ch06_watts, 3u, 0xf8u);
    dst_p[13] |= pack_right_shift_u16(src_p->ch06_watts, 5u, 0xffu);
    dst_p[14] |= pack_right_shift_u16(src_p->ch06_watts, 13u, 0x03u);
    dst_p[14] |= pack_left_shift_u8(src_p->ch07_is_on, 2u, 0x04u);
    dst_p[14] |= pack_left_shift_u8(src_p->ch07_status, 3u, 0x38u);
    dst_p[14] |= pack_left_shift_u16(src_p->ch07_watts, 6u, 0xc0u);
    dst_p[15] |= pack_right_shift_u16(src_p->ch07_watts, 2u, 0xffu);
    dst_p[16] |= pack_right_shift_u16(src_p->ch07_watts, 10u, 0x1fu);
    dst_p[16] |= pack_left_shift_u8(src_p->ch08_is_on, 5u, 0x20u);
    dst_p[16] |= pack_left_shift_u8(src_p->ch08_status, 6u, 0xc0u);
    dst_p[17] |= pack_right_shift_u8(src_p->ch08_status, 2u, 0x01u);
    dst_p[17] |= pack_left_shift_u16(src_p->ch08_watts, 1u, 0xfeu);
    dst_p[18] |= pack_right_shift_u16(src_p->ch08_watts, 7u, 0xffu);
    dst_p[19] |= pack_left_shift_u8(src_p->ch09_is_on, 0u, 0x01u);
    dst_p[19] |= pack_left_shift_u8(src_p->ch09_status, 1u, 0x0eu);
    dst_p[19] |= pack_left_shift_u16(src_p->ch09_watts, 4u, 0xf0u);
    dst_p[20] |= pack_right_shift_u16(src_p->ch09_watts, 4u, 0xffu);
    dst_p[21] |= pack_right_shift_u16(src_p->ch09_watts, 12u, 0x07u);
    dst_p[21] |= pack_left_shift_u8(src_p->ch10_is_on, 3u, 0x08u);
    dst_p[21] |= pack_left_shift_u8(src_p->ch10_status, 4u, 0x70u);
    dst_p[21] |= pack_left_shift_u16(src_p->ch10_watts, 7u, 0x80u);
    dst_p[22] |= pack_right_shift_u16(src_p->ch10_watts, 1u, 0xffu);
    dst_p[23] |= pack_right_shift_u16(src_p->ch10_watts, 9u, 0x3fu);
    dst_p[23] |= pack_left_shift_u8(src_p->ch11_is_on, 6u, 0x40u);
    dst_p[23] |= pack_left_shift_u8(src_p->ch11_status, 7u, 0x80u);
    dst_p[24] |= pack_right_shift_u8(src_p->ch11_status, 1u, 0x03u);
    dst_p[24] |= pack_left_shift_u16(src_p->ch11_watts, 2u, 0xfcu);
    dst_p[25] |= pack_right_shift_u16(src_p->ch11_watts, 6u, 0xffu);
    dst_p[26] |= pack_right_shift_u16(src_p->ch11_watts, 14u, 0x01u);
    dst_p[26] |= pack_left_shift_u8(src_p->ch12_is_on, 1u, 0x02u);
    dst_p[26] |= pack_left_shift_u8(src_p->ch12_status, 2u, 0x1cu);
    dst_p[26] |= pack_left_shift_u16(src_p->ch12_watts, 5u, 0xe0u);
    dst_p[27] |= pack_right_shift_u16(src_p->ch12_watts, 3u, 0xffu);
    dst_p[28] |= pack_right_shift_u16(src_p->ch12_watts, 11u, 0x0fu);
    dst_p[28] |= pack_left_shift_u16(src_p->supply_voltage, 4u, 0xf0u);
    dst_p[29] |= pack_right_shift_u16(src_p->supply_voltage, 4u, 0x3fu);

    return (32);
}

int cmc_can_message_channel_overview_unpack(
    struct cmc_can_message_channel_overview_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 32u) {
        return (-EINVAL);
    }

    dst_p->ch01_is_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ch01_status = unpack_right_shift_u8(src_p[0], 1u, 0x0eu);
    dst_p->ch01_watts = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
    dst_p->ch01_watts |= unpack_left_shift_u16(src_p[1], 4u, 0xffu);
    dst_p->ch01_watts |= unpack_left_shift_u16(src_p[2], 12u, 0x07u);
    dst_p->ch02_is_on = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->ch02_status = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->ch02_watts = unpack_right_shift_u16(src_p[2], 7u, 0x80u);
    dst_p->ch02_watts |= unpack_left_shift_u16(src_p[3], 1u, 0xffu);
    dst_p->ch02_watts |= unpack_left_shift_u16(src_p[4], 9u, 0x3fu);
    dst_p->ch03_is_on = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->ch03_status = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->ch03_status |= unpack_left_shift_u8(src_p[5], 1u, 0x03u);
    dst_p->ch03_watts = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->ch03_watts |= unpack_left_shift_u16(src_p[6], 6u, 0xffu);
    dst_p->ch03_watts |= unpack_left_shift_u16(src_p[7], 14u, 0x01u);
    dst_p->ch04_is_on = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
    dst_p->ch04_status = unpack_right_shift_u8(src_p[7], 2u, 0x1cu);
    dst_p->ch04_watts = unpack_right_shift_u16(src_p[7], 5u, 0xe0u);
    dst_p->ch04_watts |= unpack_left_shift_u16(src_p[8], 3u, 0xffu);
    dst_p->ch04_watts |= unpack_left_shift_u16(src_p[9], 11u, 0x0fu);
    dst_p->ch05_is_on = unpack_right_shift_u8(src_p[9], 4u, 0x10u);
    dst_p->ch05_status = unpack_right_shift_u8(src_p[9], 5u, 0xe0u);
    dst_p->ch05_watts = unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    dst_p->ch05_watts |= unpack_left_shift_u16(src_p[11], 8u, 0x7fu);
    dst_p->ch06_is_on = unpack_right_shift_u8(src_p[11], 7u, 0x80u);
    dst_p->ch06_status = unpack_right_shift_u8(src_p[12], 0u, 0x07u);
    dst_p->ch06_watts = unpack_right_shift_u16(src_p[12], 3u, 0xf8u);
    dst_p->ch06_watts |= unpack_left_shift_u16(src_p[13], 5u, 0xffu);
    dst_p->ch06_watts |= unpack_left_shift_u16(src_p[14], 13u, 0x03u);
    dst_p->ch07_is_on = unpack_right_shift_u8(src_p[14], 2u, 0x04u);
    dst_p->ch07_status = unpack_right_shift_u8(src_p[14], 3u, 0x38u);
    dst_p->ch07_watts = unpack_right_shift_u16(src_p[14], 6u, 0xc0u);
    dst_p->ch07_watts |= unpack_left_shift_u16(src_p[15], 2u, 0xffu);
    dst_p->ch07_watts |= unpack_left_shift_u16(src_p[16], 10u, 0x1fu);
    dst_p->ch08_is_on = unpack_right_shift_u8(src_p[16], 5u, 0x20u);
    dst_p->ch08_status = unpack_right_shift_u8(src_p[16], 6u, 0xc0u);
    dst_p->ch08_status |= unpack_left_shift_u8(src_p[17], 2u, 0x01u);
    dst_p->ch08_watts = unpack_right_shift_u16(src_p[17], 1u, 0xfeu);
    dst_p->ch08_watts |= unpack_left_shift_u16(src_p[18], 7u, 0xffu);
    dst_p->ch09_is_on = unpack_right_shift_u8(src_p[19], 0u, 0x01u);
    dst_p->ch09_status = unpack_right_shift_u8(src_p[19], 1u, 0x0eu);
    dst_p->ch09_watts = unpack_right_shift_u16(src_p[19], 4u, 0xf0u);
    dst_p->ch09_watts |= unpack_left_shift_u16(src_p[20], 4u, 0xffu);
    dst_p->ch09_watts |= unpack_left_shift_u16(src_p[21], 12u, 0x07u);
    dst_p->ch10_is_on = unpack_right_shift_u8(src_p[21], 3u, 0x08u);
    dst_p->ch10_status = unpack_right_shift_u8(src_p[21], 4u, 0x70u);
    dst_p->ch10_watts = unpack_right_shift_u16(src_p[21], 7u, 0x80u);
    dst_p->ch10_watts |= unpack_left_shift_u16(src_p[22], 1u, 0xffu);
    dst_p->ch10_watts |= unpack_left_shift_u16(src_p[23], 9u, 0x3fu);
    dst_p->ch11_is_on = unpack_right_shift_u8(src_p[23], 6u, 0x40u);
    dst_p->ch11_status = unpack_right_shift_u8(src_p[23], 7u, 0x80u);
    dst_p->ch11_status |= unpack_left_shift_u8(src_p[24], 1u, 0x03u);
    dst_p->ch11_watts = unpack_right_shift_u16(src_p[24], 2u, 0xfcu);
    dst_p->ch11_watts |= unpack_left_shift_u16(src_p[25], 6u, 0xffu);
    dst_p->ch11_watts |= unpack_left_shift_u16(src_p[26], 14u, 0x01u);
    dst_p->ch12_is_on = unpack_right_shift_u8(src_p[26], 1u, 0x02u);
    dst_p->ch12_status = unpack_right_shift_u8(src_p[26], 2u, 0x1cu);
    dst_p->ch12_watts = unpack_right_shift_u16(src_p[26], 5u, 0xe0u);
    dst_p->ch12_watts |= unpack_left_shift_u16(src_p[27], 3u, 0xffu);
    dst_p->ch12_watts |= unpack_left_shift_u16(src_p[28], 11u, 0x0fu);
    dst_p->supply_voltage = unpack_right_shift_u16(src_p[28], 4u, 0xf0u);
    dst_p->supply_voltage |= unpack_left_shift_u16(src_p[29], 4u, 0x3fu);

    return (0);
}

int cmc_can_message_channel_overview_init(struct cmc_can_message_channel_overview_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_channel_overview_t));

    return 0;
}

uint8_t cmc_can_message_channel_overview_ch01_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch01_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch01_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch01_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch01_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch01_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch01_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch01_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch01_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch01_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch01_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch01_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch02_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch02_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch02_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch02_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch02_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch02_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch02_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch02_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch02_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch02_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch02_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch02_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch03_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch03_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch03_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch03_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch03_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch03_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch03_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch03_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch03_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch03_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch03_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch03_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch04_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch04_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch04_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch04_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch04_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch04_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch04_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch04_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch04_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch04_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch04_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch04_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch05_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch05_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch05_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch05_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch05_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch05_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch05_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch05_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch05_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch05_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch05_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch05_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch06_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch06_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch06_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch06_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch06_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch06_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch06_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch06_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch06_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch06_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch06_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch06_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch07_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch07_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch07_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch07_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch07_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch07_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch07_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch07_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch07_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch07_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch07_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch07_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch08_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch08_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch08_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch08_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch08_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch08_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch08_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch08_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch08_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch08_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch08_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch08_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch09_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch09_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch09_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch09_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch09_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch09_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch09_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch09_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch09_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch09_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch09_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch09_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch10_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch10_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch10_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch10_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch10_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch10_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch10_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch10_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch10_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch10_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch10_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch10_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch11_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch11_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch11_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch11_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch11_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch11_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch11_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch11_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch11_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch11_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch11_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch11_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_ch12_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch12_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch12_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_ch12_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_ch12_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_ch12_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_ch12_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_ch12_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_ch12_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_ch12_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_ch12_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_ch12_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint16_t cmc_can_message_channel_overview_supply_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double cmc_can_message_channel_overview_supply_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool cmc_can_message_channel_overview_supply_voltage_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

bool cmc_can_message_channel_overview_supply_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 102.3));
}

int cmc_can_message_unit_info_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_unit_info_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->supply_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->supply_voltage, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->mcu_temp_c, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->mcu_temp_c, 4u, 0x7fu);
    dst_p[2] |= pack_left_shift_u16(src_p->total_watts, 7u, 0x80u);
    dst_p[3] |= pack_right_shift_u16(src_p->total_watts, 1u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->total_watts, 9u, 0x3fu);
    dst_p[4] |= pack_left_shift_u8(src_p->mcu_temp_out_of_range, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u16(src_p->vfref, 7u, 0x80u);
    dst_p[5] |= pack_right_shift_u16(src_p->vfref, 1u, 0xffu);

    return (6);
}

int cmc_can_message_unit_info_unpack(
    struct cmc_can_message_unit_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->supply_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->supply_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->mcu_temp_c = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->mcu_temp_c |= unpack_left_shift_u16(src_p[2], 4u, 0x7fu);
    dst_p->total_watts = unpack_right_shift_u16(src_p[2], 7u, 0x80u);
    dst_p->total_watts |= unpack_left_shift_u16(src_p[3], 1u, 0xffu);
    dst_p->total_watts |= unpack_left_shift_u16(src_p[4], 9u, 0x3fu);
    dst_p->mcu_temp_out_of_range = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->vfref = unpack_right_shift_u16(src_p[4], 7u, 0x80u);
    dst_p->vfref |= unpack_left_shift_u16(src_p[5], 1u, 0xffu);

    return (0);
}

int cmc_can_message_unit_info_init(struct cmc_can_message_unit_info_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_unit_info_t));

    return 0;
}

uint16_t cmc_can_message_unit_info_supply_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_unit_info_supply_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_unit_info_supply_voltage_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool cmc_can_message_unit_info_supply_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 40.95));
}

uint16_t cmc_can_message_unit_info_mcu_temp_c_encode(double value)
{
    return (uint16_t)((value - -40.0) / 0.1);
}

double cmc_can_message_unit_info_mcu_temp_c_decode(uint16_t value)
{
    return (((double)value * 0.1) + -40.0);
}

bool cmc_can_message_unit_info_mcu_temp_c_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

bool cmc_can_message_unit_info_mcu_temp_c_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 164.7));
}

uint16_t cmc_can_message_unit_info_total_watts_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double cmc_can_message_unit_info_total_watts_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool cmc_can_message_unit_info_total_watts_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool cmc_can_message_unit_info_total_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3276.7));
}

uint8_t cmc_can_message_unit_info_mcu_temp_out_of_range_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_unit_info_mcu_temp_out_of_range_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_unit_info_mcu_temp_out_of_range_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_unit_info_mcu_temp_out_of_range_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint16_t cmc_can_message_unit_info_vfref_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_unit_info_vfref_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_unit_info_vfref_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

bool cmc_can_message_unit_info_vfref_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 5.11));
}

int cmc_can_message_channel_overview_01_03_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_channel_overview_01_03_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ch01_is_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ch01_status, 1u, 0x0eu);
    dst_p[0] |= pack_left_shift_u16(src_p->ch01_watts, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->ch01_watts, 4u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->ch01_watts, 12u, 0x07u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch02_is_on, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch02_status, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u16(src_p->ch02_watts, 7u, 0x80u);
    dst_p[3] |= pack_right_shift_u16(src_p->ch02_watts, 1u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->ch02_watts, 9u, 0x3fu);
    dst_p[4] |= pack_left_shift_u8(src_p->ch03_is_on, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->ch03_status, 7u, 0x80u);
    dst_p[5] |= pack_right_shift_u8(src_p->ch03_status, 1u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->ch03_watts, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->ch03_watts, 6u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ch03_watts, 14u, 0x01u);

    return (8);
}

int cmc_can_message_channel_overview_01_03_unpack(
    struct cmc_can_message_channel_overview_01_03_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ch01_is_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ch01_status = unpack_right_shift_u8(src_p[0], 1u, 0x0eu);
    dst_p->ch01_watts = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
    dst_p->ch01_watts |= unpack_left_shift_u16(src_p[1], 4u, 0xffu);
    dst_p->ch01_watts |= unpack_left_shift_u16(src_p[2], 12u, 0x07u);
    dst_p->ch02_is_on = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->ch02_status = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->ch02_watts = unpack_right_shift_u16(src_p[2], 7u, 0x80u);
    dst_p->ch02_watts |= unpack_left_shift_u16(src_p[3], 1u, 0xffu);
    dst_p->ch02_watts |= unpack_left_shift_u16(src_p[4], 9u, 0x3fu);
    dst_p->ch03_is_on = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->ch03_status = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->ch03_status |= unpack_left_shift_u8(src_p[5], 1u, 0x03u);
    dst_p->ch03_watts = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->ch03_watts |= unpack_left_shift_u16(src_p[6], 6u, 0xffu);
    dst_p->ch03_watts |= unpack_left_shift_u16(src_p[7], 14u, 0x01u);

    return (0);
}

int cmc_can_message_channel_overview_01_03_init(struct cmc_can_message_channel_overview_01_03_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_channel_overview_01_03_t));

    return 0;
}

uint8_t cmc_can_message_channel_overview_01_03_ch01_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_01_03_ch01_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_01_03_ch01_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_01_03_ch01_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_01_03_ch01_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_01_03_ch01_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_01_03_ch01_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_01_03_ch01_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_01_03_ch01_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_01_03_ch01_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_01_03_ch01_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_01_03_ch01_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_01_03_ch02_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_01_03_ch02_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_01_03_ch02_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_01_03_ch02_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_01_03_ch02_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_01_03_ch02_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_01_03_ch02_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_01_03_ch02_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_01_03_ch02_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_01_03_ch02_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_01_03_ch02_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_01_03_ch02_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_01_03_ch03_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_01_03_ch03_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_01_03_ch03_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_01_03_ch03_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_01_03_ch03_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_01_03_ch03_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_01_03_ch03_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_01_03_ch03_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_01_03_ch03_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_01_03_ch03_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_01_03_ch03_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_01_03_ch03_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

int cmc_can_message_channel_overview_04_06_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_channel_overview_04_06_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ch04_is_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ch04_status, 1u, 0x0eu);
    dst_p[0] |= pack_left_shift_u16(src_p->ch04_watts, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->ch04_watts, 4u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->ch04_watts, 12u, 0x07u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch05_is_on, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch05_status, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u16(src_p->ch05_watts, 7u, 0x80u);
    dst_p[3] |= pack_right_shift_u16(src_p->ch05_watts, 1u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->ch05_watts, 9u, 0x3fu);
    dst_p[4] |= pack_left_shift_u8(src_p->ch06_is_on, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->ch06_status, 7u, 0x80u);
    dst_p[5] |= pack_right_shift_u8(src_p->ch06_status, 1u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->ch06_watts, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->ch06_watts, 6u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ch06_watts, 14u, 0x01u);

    return (8);
}

int cmc_can_message_channel_overview_04_06_unpack(
    struct cmc_can_message_channel_overview_04_06_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ch04_is_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ch04_status = unpack_right_shift_u8(src_p[0], 1u, 0x0eu);
    dst_p->ch04_watts = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
    dst_p->ch04_watts |= unpack_left_shift_u16(src_p[1], 4u, 0xffu);
    dst_p->ch04_watts |= unpack_left_shift_u16(src_p[2], 12u, 0x07u);
    dst_p->ch05_is_on = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->ch05_status = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->ch05_watts = unpack_right_shift_u16(src_p[2], 7u, 0x80u);
    dst_p->ch05_watts |= unpack_left_shift_u16(src_p[3], 1u, 0xffu);
    dst_p->ch05_watts |= unpack_left_shift_u16(src_p[4], 9u, 0x3fu);
    dst_p->ch06_is_on = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->ch06_status = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->ch06_status |= unpack_left_shift_u8(src_p[5], 1u, 0x03u);
    dst_p->ch06_watts = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->ch06_watts |= unpack_left_shift_u16(src_p[6], 6u, 0xffu);
    dst_p->ch06_watts |= unpack_left_shift_u16(src_p[7], 14u, 0x01u);

    return (0);
}

int cmc_can_message_channel_overview_04_06_init(struct cmc_can_message_channel_overview_04_06_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_channel_overview_04_06_t));

    return 0;
}

uint8_t cmc_can_message_channel_overview_04_06_ch04_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_04_06_ch04_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_04_06_ch04_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_04_06_ch04_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_04_06_ch04_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_04_06_ch04_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_04_06_ch04_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_04_06_ch04_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_04_06_ch04_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_04_06_ch04_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_04_06_ch04_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_04_06_ch04_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_04_06_ch05_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_04_06_ch05_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_04_06_ch05_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_04_06_ch05_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_04_06_ch05_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_04_06_ch05_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_04_06_ch05_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_04_06_ch05_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_04_06_ch05_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_04_06_ch05_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_04_06_ch05_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_04_06_ch05_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_04_06_ch06_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_04_06_ch06_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_04_06_ch06_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_04_06_ch06_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_04_06_ch06_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_04_06_ch06_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_04_06_ch06_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_04_06_ch06_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_04_06_ch06_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_04_06_ch06_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_04_06_ch06_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_04_06_ch06_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

int cmc_can_message_channel_overview_07_09_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_channel_overview_07_09_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ch07_is_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ch07_status, 1u, 0x0eu);
    dst_p[0] |= pack_left_shift_u16(src_p->ch07_watts, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->ch07_watts, 4u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->ch07_watts, 12u, 0x07u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch08_is_on, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch08_status, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u16(src_p->ch08_watts, 7u, 0x80u);
    dst_p[3] |= pack_right_shift_u16(src_p->ch08_watts, 1u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->ch08_watts, 9u, 0x3fu);
    dst_p[4] |= pack_left_shift_u8(src_p->ch09_is_on, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->ch09_status, 7u, 0x80u);
    dst_p[5] |= pack_right_shift_u8(src_p->ch09_status, 1u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->ch09_watts, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->ch09_watts, 6u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ch09_watts, 14u, 0x01u);

    return (8);
}

int cmc_can_message_channel_overview_07_09_unpack(
    struct cmc_can_message_channel_overview_07_09_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ch07_is_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ch07_status = unpack_right_shift_u8(src_p[0], 1u, 0x0eu);
    dst_p->ch07_watts = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
    dst_p->ch07_watts |= unpack_left_shift_u16(src_p[1], 4u, 0xffu);
    dst_p->ch07_watts |= unpack_left_shift_u16(src_p[2], 12u, 0x07u);
    dst_p->ch08_is_on = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->ch08_status = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->ch08_watts = unpack_right_shift_u16(src_p[2], 7u, 0x80u);
    dst_p->ch08_watts |= unpack_left_shift_u16(src_p[3], 1u, 0xffu);
    dst_p->ch08_watts |= unpack_left_shift_u16(src_p[4], 9u, 0x3fu);
    dst_p->ch09_is_on = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->ch09_status = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->ch09_status |= unpack_left_shift_u8(src_p[5], 1u, 0x03u);
    dst_p->ch09_watts = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->ch09_watts |= unpack_left_shift_u16(src_p[6], 6u, 0xffu);
    dst_p->ch09_watts |= unpack_left_shift_u16(src_p[7], 14u, 0x01u);

    return (0);
}

int cmc_can_message_channel_overview_07_09_init(struct cmc_can_message_channel_overview_07_09_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_channel_overview_07_09_t));

    return 0;
}

uint8_t cmc_can_message_channel_overview_07_09_ch07_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_07_09_ch07_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_07_09_ch07_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_07_09_ch07_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_07_09_ch07_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_07_09_ch07_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_07_09_ch07_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_07_09_ch07_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_07_09_ch07_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_07_09_ch07_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_07_09_ch07_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_07_09_ch07_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_07_09_ch08_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_07_09_ch08_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_07_09_ch08_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_07_09_ch08_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_07_09_ch08_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_07_09_ch08_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_07_09_ch08_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_07_09_ch08_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_07_09_ch08_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_07_09_ch08_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_07_09_ch08_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_07_09_ch08_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_07_09_ch09_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_07_09_ch09_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_07_09_ch09_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_07_09_ch09_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_07_09_ch09_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_07_09_ch09_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_07_09_ch09_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_07_09_ch09_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_07_09_ch09_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_07_09_ch09_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_07_09_ch09_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_07_09_ch09_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

int cmc_can_message_channel_overview_10_12_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_channel_overview_10_12_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ch10_is_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ch10_status, 1u, 0x0eu);
    dst_p[0] |= pack_left_shift_u16(src_p->ch10_watts, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->ch10_watts, 4u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->ch10_watts, 12u, 0x07u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch11_is_on, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->ch11_status, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u16(src_p->ch11_watts, 7u, 0x80u);
    dst_p[3] |= pack_right_shift_u16(src_p->ch11_watts, 1u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->ch11_watts, 9u, 0x3fu);
    dst_p[4] |= pack_left_shift_u8(src_p->ch12_is_on, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->ch12_status, 7u, 0x80u);
    dst_p[5] |= pack_right_shift_u8(src_p->ch12_status, 1u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->ch12_watts, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->ch12_watts, 6u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ch12_watts, 14u, 0x01u);

    return (8);
}

int cmc_can_message_channel_overview_10_12_unpack(
    struct cmc_can_message_channel_overview_10_12_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ch10_is_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ch10_status = unpack_right_shift_u8(src_p[0], 1u, 0x0eu);
    dst_p->ch10_watts = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
    dst_p->ch10_watts |= unpack_left_shift_u16(src_p[1], 4u, 0xffu);
    dst_p->ch10_watts |= unpack_left_shift_u16(src_p[2], 12u, 0x07u);
    dst_p->ch11_is_on = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->ch11_status = unpack_right_shift_u8(src_p[2], 4u, 0x70u);
    dst_p->ch11_watts = unpack_right_shift_u16(src_p[2], 7u, 0x80u);
    dst_p->ch11_watts |= unpack_left_shift_u16(src_p[3], 1u, 0xffu);
    dst_p->ch11_watts |= unpack_left_shift_u16(src_p[4], 9u, 0x3fu);
    dst_p->ch12_is_on = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->ch12_status = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->ch12_status |= unpack_left_shift_u8(src_p[5], 1u, 0x03u);
    dst_p->ch12_watts = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->ch12_watts |= unpack_left_shift_u16(src_p[6], 6u, 0xffu);
    dst_p->ch12_watts |= unpack_left_shift_u16(src_p[7], 14u, 0x01u);

    return (0);
}

int cmc_can_message_channel_overview_10_12_init(struct cmc_can_message_channel_overview_10_12_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_channel_overview_10_12_t));

    return 0;
}

uint8_t cmc_can_message_channel_overview_10_12_ch10_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_10_12_ch10_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_10_12_ch10_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_10_12_ch10_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_10_12_ch10_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_10_12_ch10_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_10_12_ch10_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_10_12_ch10_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_10_12_ch10_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_10_12_ch10_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_10_12_ch10_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_10_12_ch10_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_10_12_ch11_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_10_12_ch11_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_10_12_ch11_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_10_12_ch11_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_10_12_ch11_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_10_12_ch11_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_10_12_ch11_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_10_12_ch11_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_10_12_ch11_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_10_12_ch11_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_10_12_ch11_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_10_12_ch11_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}

uint8_t cmc_can_message_channel_overview_10_12_ch12_is_on_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_10_12_ch12_is_on_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_10_12_ch12_is_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_channel_overview_10_12_ch12_is_on_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_channel_overview_10_12_ch12_status_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_channel_overview_10_12_ch12_status_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_channel_overview_10_12_ch12_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool cmc_can_message_channel_overview_10_12_ch12_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint16_t cmc_can_message_channel_overview_10_12_ch12_watts_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double cmc_can_message_channel_overview_10_12_ch12_watts_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool cmc_can_message_channel_overview_10_12_ch12_watts_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool cmc_can_message_channel_overview_10_12_ch12_watts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 200.0));
}
