; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:esp32dev]
; platform = espressif32@^5
; board = esp32dev
; framework = arduino

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = arduino
lib_deps = 
	olikraus/U8g2@^2.36.12
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14

; Upload using one of these: 
;upload_protocol = dfu ; use USB-C port (DFU) on the board, allows serial monitor output to work
upload_protocol = stlink  ; use ST-LINK (for debugging)

; Debugging configuration
debug_tool = stlink        ; Specifies the debugger
debug_build_flags = -Og -g ; Optimize for debugging (smaller than -O0, still debuggable)

; Performance Optimization ---
board_build.f_cpu = 170000000L
build_flags =
  ;-D USBCON ; Enable USB support for serial monitor
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D HAL_PCD_MODULE_ENABLED
  -D HSE_VALUE=8000000
  -Os  ; Optimize for size instead of -O3
  -DARM_MATH_CM4
  -DARM_MATH_MATRIX_CHECK
  -DARM_MATH_ROUNDING
  -Wl,-u,_printf_float  ; Enable floating-point printf support
  -Wl,--gc-sections  ; Remove unused sections
  -ffunction-sections  ; Place each function in its own section
  -fdata-sections  ; Place each data in its own section

; Monitor settings
monitor_speed = 115200 
monitor_port = COM7 ; Set to your board's COM port (auto-detect if not specified)
