/**
 * @file cmc_can_message.h
 *
 * @brief This header file was generated by cantools version 41.3.0 Thu May 21 20:30:50 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CMC_CAN_MESSAGE_H
#define CMC_CAN_MESSAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CMC_CAN_MESSAGE_HANDSHAKE_FRAME_ID (0x64u)
#define CMC_CAN_MESSAGE_HEARTBEAT_FRAME_ID (0x65u)
#define CMC_CAN_MESSAGE_FEATURE_HORN_FRAME_ID (0xcau)
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_FRAME_ID (0xcbu)
#define CMC_CAN_MESSAGE_FEATURE_IGNITION_FRAME_ID (0xc8u)
#define CMC_CAN_MESSAGE_FEATURE_STARTER_FRAME_ID (0xc9u)
#define CMC_CAN_MESSAGE_FEATURE_LIGHT_FRAME_ID (0xccu)
#define CMC_CAN_MESSAGE_FEATURE_BRAKE_LIGHT_FRAME_ID (0xcdu)
#define CMC_CAN_MESSAGE_FEATURE_NEUTRAL_SENSOR_FRAME_ID (0xceu)
#define CMC_CAN_MESSAGE_FEATURE_OIL_PRESSURE_SENSOR_FRAME_ID (0xcfu)

/* Frame lengths in bytes. */
#define CMC_CAN_MESSAGE_HANDSHAKE_LENGTH (16u)
#define CMC_CAN_MESSAGE_HEARTBEAT_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_HORN_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_IGNITION_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_STARTER_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_LIGHT_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_BRAKE_LIGHT_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_NEUTRAL_SENSOR_LENGTH (1u)
#define CMC_CAN_MESSAGE_FEATURE_OIL_PRESSURE_SENSOR_LENGTH (1u)

/* Extended or standard frame types. */
#define CMC_CAN_MESSAGE_HANDSHAKE_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_HEARTBEAT_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_HORN_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_IGNITION_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_STARTER_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_LIGHT_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_BRAKE_LIGHT_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_NEUTRAL_SENSOR_IS_EXTENDED (0)
#define CMC_CAN_MESSAGE_FEATURE_OIL_PRESSURE_SENSOR_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_TYPE_UNKNOWN_CHOICE (0u)
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_TYPE_I_O_UNIT_CHOICE (1u)

#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_UNKNOWN_CHOICE (0u)
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_OK_CHOICE (1u)
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_WARNING_CHOICE (2u)
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_FAULT_CHOICE (3u)

/* Frame Names. */
#define CMC_CAN_MESSAGE_HANDSHAKE_NAME "HANDSHAKE"
#define CMC_CAN_MESSAGE_HEARTBEAT_NAME "HEARTBEAT"
#define CMC_CAN_MESSAGE_FEATURE_HORN_NAME "FEATURE_HORN"
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_NAME "FEATURE_DIRECTION_INDICATOR"
#define CMC_CAN_MESSAGE_FEATURE_IGNITION_NAME "FEATURE_IGNITION"
#define CMC_CAN_MESSAGE_FEATURE_STARTER_NAME "FEATURE_STARTER"
#define CMC_CAN_MESSAGE_FEATURE_LIGHT_NAME "FEATURE_LIGHT"
#define CMC_CAN_MESSAGE_FEATURE_BRAKE_LIGHT_NAME "FEATURE_BRAKE_LIGHT"
#define CMC_CAN_MESSAGE_FEATURE_NEUTRAL_SENSOR_NAME "FEATURE_NEUTRAL_SENSOR"
#define CMC_CAN_MESSAGE_FEATURE_OIL_PRESSURE_SENSOR_NAME "FEATURE_OIL_PRESSURE_SENSOR"

/* Signal Names. */
#define CMC_CAN_MESSAGE_HANDSHAKE_HW_VERSION_MAJOR_NAME "hw_version_major"
#define CMC_CAN_MESSAGE_HANDSHAKE_HW_VERSION_MINOR_NAME "hw_version_minor"
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_ID_NAME "unit_id"
#define CMC_CAN_MESSAGE_HANDSHAKE_UNIT_TYPE_NAME "unit_type"
#define CMC_CAN_MESSAGE_HANDSHAKE_FW_VERSION_MAJOR_NAME "fw_version_major"
#define CMC_CAN_MESSAGE_HANDSHAKE_FW_VERSION_MINOR_NAME "fw_version_minor"
#define CMC_CAN_MESSAGE_HANDSHAKE_GC_DATETIME_NAME "gc_datetime"
#define CMC_CAN_MESSAGE_HANDSHAKE_GC_HASH_NAME "gc_hash"
#define CMC_CAN_MESSAGE_HEARTBEAT_UNIT_ID_NAME "unit_id"
#define CMC_CAN_MESSAGE_HEARTBEAT_SYSTEM_STATE_NAME "system_state"
#define CMC_CAN_MESSAGE_FEATURE_HORN_HORN_ON_NAME "horn_on"
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_TURN_SIGNAL_ON_NAME "turn_signal_on"
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_TURN_SIGNAL_DIRECTION_NAME "turn_signal_direction"
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_TURN_SIGNAL_POSITION_NAME "turn_signal_position"
#define CMC_CAN_MESSAGE_FEATURE_DIRECTION_INDICATOR_DASHBOARD_ONLY_NAME "dashboard_only"
#define CMC_CAN_MESSAGE_FEATURE_IGNITION_IGNITION_ON_NAME "ignition_on"
#define CMC_CAN_MESSAGE_FEATURE_STARTER_STARTER_ON_NAME "starter_on"
#define CMC_CAN_MESSAGE_FEATURE_LIGHT_PARK_ON_NAME "park_on"
#define CMC_CAN_MESSAGE_FEATURE_LIGHT_LOW_BEAM_ON_NAME "low_beam_on"
#define CMC_CAN_MESSAGE_FEATURE_LIGHT_HIGH_BEAM_ON_NAME "high_beam_on"
#define CMC_CAN_MESSAGE_FEATURE_BRAKE_LIGHT_BRAKE_LIGHT_ON_NAME "brake_light_on"
#define CMC_CAN_MESSAGE_FEATURE_NEUTRAL_SENSOR_NEUTRAL_ENGAGED_NAME "neutral_engaged"
#define CMC_CAN_MESSAGE_FEATURE_OIL_PRESSURE_SENSOR_OIL_PRESSURE_LOW_DETECTED_NAME "oil_pressure_low_detected"

/**
 * Signals in message HANDSHAKE.
 *
 * Startup init to check ID and FW for all units, inititate reset or reconfig if needed
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_handshake_t {
    /**
     * Hardware major version
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hw_version_major;

    /**
     * Hardware minor version
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hw_version_minor;

    /**
     * Unique ID for the source unit
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t unit_id;

    /**
     * Unit type
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t unit_type;

    /**
     * Firmware major version, should listed for compability to ensure units can be combined
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fw_version_major;

    /**
     * Firmware minor version, for info only
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fw_version_minor;

    /**
     * All global configs across all units must be the same, datetime is when the config was created/updated, if not the same across units or if missing, the most recent updated config is to be used and passed over to units with old config
     *
     * Range: 0..4294967295 (0..4294967295 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t gc_datetime;

    /**
     * All global configs across all units must be the same, this hash represent global config checksum
     *
     * Range: 0..4294967295 (0..4294967295 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t gc_hash;
};

/**
 * Signals in message HEARTBEAT.
 *
 * Poll on system frequently to identify missing units or mishaps
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_heartbeat_t {
    /**
     * Unique ID for the source unit
     *
     * Range: 0..63 (0..63 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t unit_id;

    /**
     * Report system state for taking action if not OK
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t system_state;
};

/**
 * Signals in message FEATURE_HORN.
 *
 * Turn horn on/off
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_horn_t {
    /**
     * 0=off, 1=on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t horn_on;
};

/**
 * Signals in message FEATURE_DIRECTION_INDICATOR.
 *
 * Turn direction indicators on/off, send also info for left, righ or both (hazard) and optionally if to be turned of only for front or rear, normally should be both. Separate for turning on indicator only, to be used for startup animation or check that dashboard indicator bulb works
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_direction_indicator_t {
    /**
     * 0=off, 1=on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t turn_signal_on;

    /**
     * 0=left, 1=right, 2=both
     *
     * Range: 0..2 (0..2 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t turn_signal_direction;

    /**
     * 0=front, 1=rear, 2=both
     *
     * Range: 0..2 (0..2 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t turn_signal_position;

    /**
     * 0=normal operation, 1=only affect dashboard warning indicator
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t dashboard_only;
};

/**
 * Signals in message FEATURE_IGNITION.
 *
 * Control ignition status
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_ignition_t {
    /**
     * 0=off, 1=on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ignition_on;
};

/**
 * Signals in message FEATURE_STARTER.
 *
 * Control starter motor
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_starter_t {
    /**
     * 0=off, 1=engaged (on)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t starter_on;
};

/**
 * Signals in message FEATURE_LIGHT.
 *
 * Lights: park, low beam and high beam
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_light_t {
    /**
     * 0 = off, 1=on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t park_on;

    /**
     * 0 = off, 1=on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t low_beam_on;

    /**
     * 0 = off, 1=on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t high_beam_on;
};

/**
 * Signals in message FEATURE_BRAKE_LIGHT.
 *
 * Lights: Brake Light
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_brake_light_t {
    /**
     * 0 = off, 1 = on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_light_on;
};

/**
 * Signals in message FEATURE_NEUTRAL_SENSOR.
 *
 * Neutral sensor should activate dashboard light
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_neutral_sensor_t {
    /**
     * 0 = off, 1 = on
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t neutral_engaged;
};

/**
 * Signals in message FEATURE_OIL_PRESSURE_SENSOR.
 *
 * Oil Pressure Sensor should activate warning light on dash
 *
 * All signal values are as on the CAN bus.
 */
struct cmc_can_message_feature_oil_pressure_sensor_t {
    /**
     * 0 = normal operation, 1 = low pressure detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t oil_pressure_low_detected;
};

/**
 * Pack message HANDSHAKE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_handshake_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_handshake_t *src_p,
    size_t size);

/**
 * Unpack message HANDSHAKE.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_handshake_unpack(
    struct cmc_can_message_handshake_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HANDSHAKE.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_handshake_init(struct cmc_can_message_handshake_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_hw_version_major_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_hw_version_major_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_major_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_major_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_hw_version_minor_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_hw_version_minor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_minor_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_hw_version_minor_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_unit_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_unit_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_id_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_id_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_unit_type_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_unit_type_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_type_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_unit_type_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_fw_version_major_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_fw_version_major_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_major_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_major_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_handshake_fw_version_minor_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_fw_version_minor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_minor_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_fw_version_minor_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t cmc_can_message_handshake_gc_datetime_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_gc_datetime_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_datetime_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_datetime_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t cmc_can_message_handshake_gc_hash_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_handshake_gc_hash_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_hash_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_handshake_gc_hash_is_in_phys_range(double value);

/**
 * Pack message HEARTBEAT.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_heartbeat_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_heartbeat_t *src_p,
    size_t size);

/**
 * Unpack message HEARTBEAT.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_heartbeat_unpack(
    struct cmc_can_message_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HEARTBEAT.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_heartbeat_init(struct cmc_can_message_heartbeat_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_heartbeat_unit_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_heartbeat_unit_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_unit_id_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_unit_id_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_heartbeat_system_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_heartbeat_system_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_system_state_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_heartbeat_system_state_is_in_phys_range(double value);

/**
 * Pack message FEATURE_HORN.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_horn_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_horn_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_HORN.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_horn_unpack(
    struct cmc_can_message_feature_horn_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_HORN.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_horn_init(struct cmc_can_message_feature_horn_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_horn_horn_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_horn_horn_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_horn_horn_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_horn_horn_on_is_in_phys_range(double value);

/**
 * Pack message FEATURE_DIRECTION_INDICATOR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_direction_indicator_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_direction_indicator_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_DIRECTION_INDICATOR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_direction_indicator_unpack(
    struct cmc_can_message_feature_direction_indicator_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_DIRECTION_INDICATOR.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_direction_indicator_init(struct cmc_can_message_feature_direction_indicator_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_direction_indicator_turn_signal_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_direction_indicator_turn_signal_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_turn_signal_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_turn_signal_on_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_direction_indicator_turn_signal_direction_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_direction_indicator_turn_signal_direction_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_turn_signal_direction_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_turn_signal_direction_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_direction_indicator_turn_signal_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_direction_indicator_turn_signal_position_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_turn_signal_position_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_turn_signal_position_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_direction_indicator_dashboard_only_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_direction_indicator_dashboard_only_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_dashboard_only_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_direction_indicator_dashboard_only_is_in_phys_range(double value);

/**
 * Pack message FEATURE_IGNITION.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_ignition_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_ignition_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_IGNITION.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_ignition_unpack(
    struct cmc_can_message_feature_ignition_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_IGNITION.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_ignition_init(struct cmc_can_message_feature_ignition_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_ignition_ignition_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_ignition_ignition_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_ignition_ignition_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_ignition_ignition_on_is_in_phys_range(double value);

/**
 * Pack message FEATURE_STARTER.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_starter_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_starter_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_STARTER.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_starter_unpack(
    struct cmc_can_message_feature_starter_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_STARTER.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_starter_init(struct cmc_can_message_feature_starter_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_starter_starter_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_starter_starter_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_starter_starter_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_starter_starter_on_is_in_phys_range(double value);

/**
 * Pack message FEATURE_LIGHT.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_light_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_light_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_LIGHT.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_light_unpack(
    struct cmc_can_message_feature_light_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_LIGHT.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_light_init(struct cmc_can_message_feature_light_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_light_park_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_light_park_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_light_park_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_light_park_on_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_light_low_beam_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_light_low_beam_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_light_low_beam_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_light_low_beam_on_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_light_high_beam_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_light_high_beam_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_light_high_beam_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_light_high_beam_on_is_in_phys_range(double value);

/**
 * Pack message FEATURE_BRAKE_LIGHT.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_brake_light_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_brake_light_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_BRAKE_LIGHT.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_brake_light_unpack(
    struct cmc_can_message_feature_brake_light_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_BRAKE_LIGHT.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_brake_light_init(struct cmc_can_message_feature_brake_light_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_brake_light_brake_light_on_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_brake_light_brake_light_on_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_brake_light_brake_light_on_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_brake_light_brake_light_on_is_in_phys_range(double value);

/**
 * Pack message FEATURE_NEUTRAL_SENSOR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_neutral_sensor_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_neutral_sensor_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_NEUTRAL_SENSOR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_neutral_sensor_unpack(
    struct cmc_can_message_feature_neutral_sensor_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_NEUTRAL_SENSOR.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_neutral_sensor_init(struct cmc_can_message_feature_neutral_sensor_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_neutral_sensor_neutral_engaged_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_neutral_sensor_neutral_engaged_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_neutral_sensor_neutral_engaged_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_neutral_sensor_neutral_engaged_is_in_phys_range(double value);

/**
 * Pack message FEATURE_OIL_PRESSURE_SENSOR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int cmc_can_message_feature_oil_pressure_sensor_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_oil_pressure_sensor_t *src_p,
    size_t size);

/**
 * Unpack message FEATURE_OIL_PRESSURE_SENSOR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int cmc_can_message_feature_oil_pressure_sensor_unpack(
    struct cmc_can_message_feature_oil_pressure_sensor_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FEATURE_OIL_PRESSURE_SENSOR.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int cmc_can_message_feature_oil_pressure_sensor_init(struct cmc_can_message_feature_oil_pressure_sensor_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool cmc_can_message_feature_oil_pressure_sensor_oil_pressure_low_detected_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
