/**
 * @file cmc_can_message.c
 *
 * @brief This source file was generated by cantools version 41.3.0 Sun May 10 23:40:12 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "cmc_can_message.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int cmc_can_message_handshake_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_handshake_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 16);

    dst_p[0] |= pack_left_shift_u8(src_p->hw_version_major, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->hw_version_minor, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->unit_id, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->unit_type, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->fw_version_major, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->fw_version_minor, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u32(src_p->gc_datetime, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->gc_datetime, 8u, 0xffu);
    dst_p[8] |= pack_right_shift_u32(src_p->gc_datetime, 16u, 0xffu);
    dst_p[9] |= pack_right_shift_u32(src_p->gc_datetime, 24u, 0xffu);
    dst_p[10] |= pack_left_shift_u32(src_p->gc_hash, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(src_p->gc_hash, 8u, 0xffu);
    dst_p[12] |= pack_right_shift_u32(src_p->gc_hash, 16u, 0xffu);
    dst_p[13] |= pack_right_shift_u32(src_p->gc_hash, 24u, 0xffu);

    return (16);
}

int cmc_can_message_handshake_unpack(
    struct cmc_can_message_handshake_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 16u) {
        return (-EINVAL);
    }

    dst_p->hw_version_major = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->hw_version_minor = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->unit_id = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->unit_type = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->fw_version_major = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->fw_version_minor = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->gc_datetime = unpack_right_shift_u32(src_p[6], 0u, 0xffu);
    dst_p->gc_datetime |= unpack_left_shift_u32(src_p[7], 8u, 0xffu);
    dst_p->gc_datetime |= unpack_left_shift_u32(src_p[8], 16u, 0xffu);
    dst_p->gc_datetime |= unpack_left_shift_u32(src_p[9], 24u, 0xffu);
    dst_p->gc_hash = unpack_right_shift_u32(src_p[10], 0u, 0xffu);
    dst_p->gc_hash |= unpack_left_shift_u32(src_p[11], 8u, 0xffu);
    dst_p->gc_hash |= unpack_left_shift_u32(src_p[12], 16u, 0xffu);
    dst_p->gc_hash |= unpack_left_shift_u32(src_p[13], 24u, 0xffu);

    return (0);
}

int cmc_can_message_handshake_init(struct cmc_can_message_handshake_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_handshake_t));

    return 0;
}

uint8_t cmc_can_message_handshake_hw_version_major_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_hw_version_major_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_hw_version_major_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_hw_version_major_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_hw_version_minor_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_hw_version_minor_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_hw_version_minor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_hw_version_minor_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_unit_id_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_unit_id_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_unit_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_unit_id_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_unit_type_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_unit_type_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_unit_type_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_unit_type_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_fw_version_major_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_fw_version_major_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_fw_version_major_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_fw_version_major_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t cmc_can_message_handshake_fw_version_minor_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_handshake_fw_version_minor_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_fw_version_minor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_fw_version_minor_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint32_t cmc_can_message_handshake_gc_datetime_encode(double value)
{
    return (uint32_t)(value);
}

double cmc_can_message_handshake_gc_datetime_decode(uint32_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_gc_datetime_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_gc_datetime_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967295.0));
}

uint32_t cmc_can_message_handshake_gc_hash_encode(double value)
{
    return (uint32_t)(value);
}

double cmc_can_message_handshake_gc_hash_decode(uint32_t value)
{
    return ((double)value);
}

bool cmc_can_message_handshake_gc_hash_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_handshake_gc_hash_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967295.0));
}

int cmc_can_message_heartbeat_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->unit_id, 0u, 0x3fu);
    dst_p[0] |= pack_left_shift_u8(src_p->system_state, 6u, 0xc0u);

    return (1);
}

int cmc_can_message_heartbeat_unpack(
    struct cmc_can_message_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->unit_id = unpack_right_shift_u8(src_p[0], 0u, 0x3fu);
    dst_p->system_state = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);

    return (0);
}

int cmc_can_message_heartbeat_init(struct cmc_can_message_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_heartbeat_t));

    return 0;
}

uint8_t cmc_can_message_heartbeat_unit_id_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_heartbeat_unit_id_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_heartbeat_unit_id_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool cmc_can_message_heartbeat_unit_id_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 63.0));
}

uint8_t cmc_can_message_heartbeat_system_state_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_heartbeat_system_state_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_heartbeat_system_state_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool cmc_can_message_heartbeat_system_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 3.0));
}

int cmc_can_message_feature_horn_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_horn_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->value_on_off, 0u, 0x01u);

    return (1);
}

int cmc_can_message_feature_horn_unpack(
    struct cmc_can_message_feature_horn_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->value_on_off = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int cmc_can_message_feature_horn_init(struct cmc_can_message_feature_horn_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_horn_t));

    return 0;
}

uint8_t cmc_can_message_feature_horn_value_on_off_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_horn_value_on_off_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_horn_value_on_off_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool cmc_can_message_feature_horn_value_on_off_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int cmc_can_message_feature_direction_indicator_pack(
    uint8_t *dst_p,
    const struct cmc_can_message_feature_direction_indicator_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->value_on_off, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->value_left_right_both, 1u, 0x06u);
    dst_p[0] |= pack_left_shift_u8(src_p->value_front_rear_both, 3u, 0x18u);
    dst_p[0] |= pack_left_shift_u8(src_p->value_dashboard_only, 5u, 0x20u);

    return (1);
}

int cmc_can_message_feature_direction_indicator_unpack(
    struct cmc_can_message_feature_direction_indicator_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->value_on_off = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->value_left_right_both = unpack_right_shift_u8(src_p[0], 1u, 0x06u);
    dst_p->value_front_rear_both = unpack_right_shift_u8(src_p[0], 3u, 0x18u);
    dst_p->value_dashboard_only = unpack_right_shift_u8(src_p[0], 5u, 0x20u);

    return (0);
}

int cmc_can_message_feature_direction_indicator_init(struct cmc_can_message_feature_direction_indicator_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmc_can_message_feature_direction_indicator_t));

    return 0;
}

uint8_t cmc_can_message_feature_direction_indicator_value_on_off_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_value_on_off_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_value_on_off_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_direction_indicator_value_on_off_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t cmc_can_message_feature_direction_indicator_value_left_right_both_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_value_left_right_both_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_value_left_right_both_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool cmc_can_message_feature_direction_indicator_value_left_right_both_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 2.0));
}

uint8_t cmc_can_message_feature_direction_indicator_value_front_rear_both_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_value_front_rear_both_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_value_front_rear_both_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool cmc_can_message_feature_direction_indicator_value_front_rear_both_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 2.0));
}

uint8_t cmc_can_message_feature_direction_indicator_value_dashboard_only_encode(double value)
{
    return (uint8_t)(value);
}

double cmc_can_message_feature_direction_indicator_value_dashboard_only_decode(uint8_t value)
{
    return ((double)value);
}

bool cmc_can_message_feature_direction_indicator_value_dashboard_only_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool cmc_can_message_feature_direction_indicator_value_dashboard_only_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}
